/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hardware_system;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DERRICK
 */
public class sw_act extends javax.swing.JFrame {
    int pX, pY;
    Connection conn = null;
    Statement stm = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form sw_act
     */
    public sw_act() {
        
        // check();
         initComponents();
         iconMethod();
         success.setVisible(false);
         Fail.setVisible(false);
         
    }
    public void iconMethod()
    {
    this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/applications.png")));
    }
    
    private void magic()
    {
       String date = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new java.util.Date());
       final ImageIcon icon = new ImageIcon("/icons/applications.png");
       
       try{

            String newTeacher = "INSERT INTO `activation`(`name`, `reg_date`, `status`) VALUES (?,?,?)";
            pst = conn.prepareStatement(newTeacher);
            pst.setString(1, reg_to.getText());
            pst.setString(2, date);
            pst.setString(3, "active");
            pst.execute();
            int p = JOptionPane.showConfirmDialog(null, "Do you want to launch the software now?", "Activation successful!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icon);
             if (p == JOptionPane.YES_OPTION) 
             {
                
                
                    Progress2 i = new Progress2();
                    i.setVisible(true);
                    this.dispose();

                
             } else if(p==JOptionPane.NO_OPTION) 
             {
                System.exit(0);
             }
        }catch(Exception e)
        {
        e.printStackTrace();
        }             
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        key1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        key2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        key3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        key4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        key5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Fail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        reg_to = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/software.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/management_lock.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        key1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key1KeyTyped(evt);
            }
        });
        getContentPane().add(key1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("+");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, 20));

        key2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key2KeyTyped(evt);
            }
        });
        getContentPane().add(key2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 60, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("+");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, 20));

        key3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key3KeyTyped(evt);
            }
        });
        getContentPane().add(key3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("+");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 20));

        key4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                key4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key4KeyTyped(evt);
            }
        });
        getContentPane().add(key4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 60, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("+");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 20));

        key5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                key5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key5KeyTyped(evt);
            }
        });
        getContentPane().add(key5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 60, -1));

        jButton1.setText("ACTIVATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 90, 30));

        success.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/Success.png"))); // NOI18N
        getContentPane().add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/Key-icon.png"))); // NOI18N
        jLabel9.setText("Registered to:");
        jLabel9.setToolTipText("Order for a Key online");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 60, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/cancel-icon.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/Phone.png"))); // NOI18N
        jLabel11.setToolTipText("Call for help");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 40, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter the activation code in the boxes below");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 270, -1));

        Fail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/close_16.png"))); // NOI18N
        Fail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FailMouseClicked(evt);
            }
        });
        getContentPane().add(Fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Registered to:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, -1));
        getContentPane().add(reg_to, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/admin_back.jpg"))); // NOI18N
        jLabel1.setText("+");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        setSize(new java.awt.Dimension(521, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "F";
            float f = Float.valueOf(val);
            this.setOpacity(f);

            try {
                Thread.sleep(100);

            } catch (Exception e) {

            }

        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        try{
            String URL ="www.twitter.com/Shazka_Systems";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }catch(Exception e)
        {
        e.printStackTrace();
        }
       /* Date date1=jDateChooser1.getDate();
      Date date2=jDateChooser2.getDate();
             long timdiff=date2.getTime()-date1.getTime();
             jTextField1.setText(""+(timdiff/(1000*60*60*24)));*/
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        final ImageIcon icon = new ImageIcon("/icons/applications.png");
        JOptionPane.showMessageDialog( this, "Contact our customer care desk\n 0714950155.","Get help", JOptionPane.INFORMATION_MESSAGE, icon);
               
    }//GEN-LAST:event_jLabel11MouseClicked

    private void key1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key1KeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) 
        {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_key1KeyTyped

    private void key1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key1KeyReleased
        String num = key1.getText();
        int length = num.length();
        if(length ==4)
        {
             key1.transferFocus();
        }
    }//GEN-LAST:event_key1KeyReleased

    private void key2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key2KeyReleased
        String num = key2.getText();
        int length = num.length();
        if(length ==4)
        {
            key2.transferFocus();
        }
    }//GEN-LAST:event_key2KeyReleased

    private void key3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key3KeyReleased
        String num = key3.getText();
        int length = num.length();
        if(length ==4)
        {
            key3.transferFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_key3KeyReleased

    private void key4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key4KeyReleased
        String num = key4.getText();
        int length = num.length();
        if(length ==4)
        {
            key4.transferFocus();
        }
    }//GEN-LAST:event_key4KeyReleased

    private void key5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key5KeyReleased
        String num = key5.getText();
        int length = num.length();
        if(length ==4)
        {
            success.setVisible(false);
            key5.transferFocus();
           
        }
    }//GEN-LAST:event_key5KeyReleased

    private void key5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key5KeyPressed
        
    }//GEN-LAST:event_key5KeyPressed

    private void key4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key4KeyPressed
        
    }//GEN-LAST:event_key4KeyPressed

    private void FailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FailMouseClicked
        key1.setText("");
        key2.setText("");
        key3.setText("");
        key4.setText("");
        key5.setText("");
    }//GEN-LAST:event_FailMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Connect Connect = new Connect();
       conn = Connect.connectdb();
       
       String date = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(new java.util.Date());
       final ImageIcon icon = new ImageIcon("/icons/applications.png");
        
       if(reg_to.getText().equals(""))
       {
        JOptionPane.showMessageDialog( null, "You must fill your name or company name","Error! Missing field", JOptionPane.ERROR_MESSAGE);
        return; 
       }
       if(key1.getText().equals("")|| key2.getText().equals("") ||key3.getText().equals("")||key4.getText().equals("") ||key5.getText().equals(""))
       {
        JOptionPane.showMessageDialog( null, "The code entered seems incorrect","Error! Invalid code", JOptionPane.ERROR_MESSAGE);
        return; 
       }
       
       String on=key1.getText().trim();
       String tw=key2.getText().trim();
       String thr=key3.getText().trim();
       String fo=key4.getText().trim();
       String fve=key5.getText().trim();
       
        if(on.equals("1495") && tw.equals("0155")&& thr.equals("3168")&&fo.equals("4469")&&fve.equals("2355"))
       {
           magic();
           success.setVisible(true);
         Fail.setVisible(false);
       }else
       if(on.equals("W269N") && tw.equals("WFGWX")&& thr.equals("YVC9B")&&fo.equals("4J6C9")&&fve.equals("T83GX"))
       {
           magic();
           success.setVisible(true);
         Fail.setVisible(false);
       }else if(on.equals("MH37W") && tw.equals("N47XK")&& thr.equals("V7XM9")&&fo.equals("C7227")&&fve.equals("GCQG9"))
       {
           magic();
           success.setVisible(true);
         Fail.setVisible(false);
       }else if(on.equals("NPPR9") && tw.equals("FWDCX")&& thr.equals("D2C8J")&&fo.equals("H872K")&&fve.equals("2YT43"))
       {
           magic();
           success.setVisible(true);
         Fail.setVisible(false);
       }else if(on.equals("DPH2V") && tw.equals("TTNVB")&& thr.equals("4X9Q3")&&fo.equals("TJR4H")&&fve.equals("KHJW4"))
       {
           magic();
           success.setVisible(true);
         Fail.setVisible(false);
       }else{
           JOptionPane.showMessageDialog( null, "You must type the code correctly. \nIf key doesnt work contact the supplier - 0714950155 ","Error! Wrong Code", JOptionPane.ERROR_MESSAGE);
       }
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void key2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key2KeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) 
        {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_key2KeyTyped

    private void key3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key3KeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) 
        {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_key3KeyTyped

    private void key4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key4KeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) 
        {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }
    }//GEN-LAST:event_key4KeyTyped

    private void key5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key5KeyTyped
        char keyChar = evt.getKeyChar();
        if (Character.isLowerCase(keyChar)) 
        {
          evt.setKeyChar(Character.toUpperCase(keyChar));
        }// TODO add your handling code here:
    }//GEN-LAST:event_key5KeyTyped

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        pX = evt.getX();
        pY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - pX,
                            this.getLocation().y + evt.getY() - pY);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sw_act.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sw_act.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sw_act.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sw_act.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sw_act().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField key1;
    private javax.swing.JTextField key2;
    private javax.swing.JTextField key3;
    private javax.swing.JTextField key4;
    private javax.swing.JTextField key5;
    private javax.swing.JTextField reg_to;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables


}
